[package]
name = "irene"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
nom = "8.0.0"
nom_locate = "5.0.0"
serenity = { version = "0.12.4", features = ["client"] }
tokio = { version = "1.45.1", features = ["full"] }
